name: Daily AI Agents Digest

on:
  schedule:
    - cron: '10 17 * * *'
    
jobs:
  run-digest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the daily digest script
      env:
        GEMINI_API_KEY_naikshriyans: ${{ secrets.GEMINI_API_KEY_naikshriyans }}
        GEMINI_API_KEY_shriyansnaik: ${{ secrets.GEMINI_API_KEY_shriyansnaik }}
        GEMINI_API_KEY_adityapatil: ${{ secrets.GEMINI_API_KEY_adityapatil }}
        GEMINI_API_KEY_akshatsharma: ${{ secrets.GEMINI_API_KEY_akshatsharma }}
        GEMINI_API_KEY_glacias: ${{ secrets.GEMINI_API_KEY_glacias }}
        GEMINI_API_KEY_jbeans: ${{ secrets.GEMINI_API_KEY_jbeans }}
        GEMINI_API_KEY_somaiya: ${{ secrets.GEMINI_API_KEY_somaiya }}
        GEMINI_API_KEY_splitit: ${{ secrets.GEMINI_API_KEY_splitit }}
        GEMINI_API_KEY_shriyansresearch: ${{ secrets.GEMINI_API_KEY_shriyansresearch }}
        GEMINI_BASE_API: ${{ secrets.GEMINI_BASE_API }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_EMAIL_PASSWORD: ${{ secrets.SENDER_EMAIL_PASSWORD }}
        MAIL_LIST: ${{ secrets.MAIL_LIST }}
      run: python main.py
