name: Daily AI Agents Digest

on:
  schedule:
    - cron: '30 4 * * *'

  # Manually trigger the workflow
  workflow_dispatch:  # This enables the manual trigger
    
jobs:
  run-digest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the daily digest script
      env:
        GEMINI_API_KEY_NAIKSHRIYANS: ${{ secrets.GEMINI_API_KEY_NAIKSHRIYANS }}
        GEMINI_API_KEY_SHRIYANSNAIK: ${{ secrets.GEMINI_API_KEY_SHRIYANSNAIK }}
        GEMINI_API_KEY_ADITYAPATIL: ${{ secrets.GEMINI_API_KEY_ADITYAPATIL }}
        GEMINI_API_KEY_AKSHATSHARMA: ${{ secrets.GEMINI_API_KEY_AKSHATSHARMA }}
        GEMINI_API_KEY_GLACIAS: ${{ secrets.GEMINI_API_KEY_GLACIAS }}
        GEMINI_API_KEY_JBEANS: ${{ secrets.GEMINI_API_KEY_JBEANS }}
        GEMINI_API_KEY_SOMAIYA: ${{ secrets.GEMINI_API_KEY_SOMAIYA }}
        GEMINI_API_KEY_SPLITIT: ${{ secrets.GEMINI_API_KEY_SPLITIT }}
        GEMINI_API_KEY_SHRIYANSRESEARCH: ${{ secrets.GEMINI_API_KEY_SHRIYANSRESEARCH }}
        GEMINI_BASE_API: ${{ secrets.GEMINI_BASE_API }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_EMAIL_PASSWORD: ${{ secrets.SENDER_EMAIL_PASSWORD }}
        AGENT_MAIL_LIST: ${{ secrets.AGENT_MAIL_LIST }}
        KAVERI: ${{ secrets.KAVERI }}
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      run: python main.py
